# Generated by Django 6.0.5 on 2026-05-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='classe',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
