# Generated by Django 6.0.5 on 2026-05-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaire', '0002_alter_etudiant_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filiere',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
