# Generated by Django 6.0.5 on 2026-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaire', '0003_alter_module_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
